import { LegendSet } from '../models/legend-set.model';

export const d2LegendSets: LegendSet[] = [
    {
        created: '2019-01-17T10:12:22.781',
        lastUpdated: '2022-03-04T11:21:33.437',
        name: 'Drop out rates (-100-0, 0-10, 10-100)',
        href: 'https://tland.dhis2.udsm.ac.tz/api/36/legendSets/HpqwUDvTbJT',
        id: 'HpqwUDvTbJT',
        displayName: 'Drop out rates (-100-0, 0-10, 10-100)',
        publicAccess: 'rw------',
        sharing: {
            owner: 'KAZQ2jHJAhx',
            external: false,
            users: {},
            userGroups: {},
            public: 'rw------',
        },
        externalAccess: false,
        favorite: false,
        lastUpdatedBy: {
            displayName: 'Josephat Julius',
            name: 'Josephat Julius',
            id: 'ELelSS7HfqW',
            username: 'josephatjulius',
        },
        access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
        },
        createdBy: {
            displayName: 'Wilfred Senyoni',
            name: 'Wilfred Senyoni',
            id: 'KAZQ2jHJAhx',
            username: 'senyoni',
        },
        user: {
            displayName: 'Wilfred Senyoni',
            name: 'Wilfred Senyoni',
            id: 'KAZQ2jHJAhx',
            username: 'senyoni',
        },
        favorites: [],
        userGroupAccesses: [],
        attributeValues: [],
        legends: [
            {
                lastUpdated: '2022-03-04T11:21:33.437',
                id: 'S3jgoE3JSQY',
                created: '2022-03-04T11:21:33.437',
                name: '0 - 10',
                endValue: 10.0,
                color: '#0CFA19',
                displayName: '0 - 10',
                externalAccess: false,
                startValue: 0.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T11:21:33.438',
                id: 'QqOUuAGWQJg',
                created: '2022-03-04T11:21:33.438',
                name: '-100 - 0',
                endValue: 0.0,
                color: '#FFFFFF',
                displayName: '-100 - 0',
                externalAccess: false,
                startValue: -100.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T11:21:33.438',
                id: 'm9hkjaFdfJn',
                created: '2022-03-04T11:21:33.438',
                name: '10 - 100',
                endValue: 100.0,
                color: '#F60404',
                displayName: '10 - 100',
                externalAccess: false,
                startValue: 10.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
        ],
        translations: [],
        userAccesses: [],
    },
    {
        code: 'Severe Malaria Incidence',
        created: '2019-06-27T20:42:15.436',
        lastUpdated: '2022-03-04T12:17:05.697',
        name: 'Severe Malaria Incidence (0-10,10-25,25-50,50-100,100-500)',
        href: 'https://tland.dhis2.udsm.ac.tz/api/36/legendSets/RVJUoXd7DOH',
        id: 'RVJUoXd7DOH',
        displayName: 'Severe Malaria Incidence (0-10,10-25,25-50,50-100,100-500)',
        publicAccess: 'rw------',
        sharing: {
            owner: 'K5zs1PyrqeC',
            external: false,
            users: {},
            userGroups: {},
            public: 'rw------',
        },
        externalAccess: false,
        favorite: false,
        lastUpdatedBy: {
            displayName: 'Josephat Julius',
            name: 'Josephat Julius',
            id: 'ELelSS7HfqW',
            username: 'josephatjulius',
        },
        access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
        },
        createdBy: {
            displayName: 'Mwita Sogorya',
            name: 'Mwita Sogorya',
            id: 'K5zs1PyrqeC',
            username: 'msogorya',
        },
        user: {
            displayName: 'Mwita Sogorya',
            name: 'Mwita Sogorya',
            id: 'K5zs1PyrqeC',
            username: 'msogorya',
        },
        favorites: [],
        userGroupAccesses: [],
        attributeValues: [],
        legends: [
            {
                lastUpdated: '2022-03-04T12:17:05.697',
                id: 'YfW9Ac6rZQM',
                created: '2022-03-04T12:17:05.697',
                name: '50 - < 100',
                endValue: 100.0,
                color: '#336699',
                displayName: '50 - < 100',
                externalAccess: false,
                startValue: 50.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T12:17:05.698',
                id: 'Y4OXQDfqGiU',
                created: '2022-03-04T12:17:05.698',
                name: '10 - < 25',
                endValue: 25.0,
                color: '#0099cc',
                displayName: '10 - < 25',
                externalAccess: false,
                startValue: 10.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T12:17:05.698',
                id: 'q8W338JwsHv',
                created: '2022-03-04T12:17:05.698',
                name: '25 - < 50',
                endValue: 50.0,
                color: '#00ccff',
                displayName: '25 - < 50',
                externalAccess: false,
                startValue: 25.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T12:17:05.698',
                id: 'UvNEko3QS6v',
                created: '2022-03-04T12:17:05.698',
                name: '>100',
                endValue: 500.0,
                color: '#E8240E',
                displayName: '>100',
                externalAccess: false,
                startValue: 100.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
            {
                lastUpdated: '2022-03-04T12:17:05.698',
                id: 'K7DmrnXep3g',
                created: '2022-03-04T12:17:05.698',
                name: '<10',
                endValue: 10.0,
                color: '#399313',
                displayName: '<10',
                externalAccess: false,
                startValue: 0.0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                favorite: false,
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                favorites: [],
                translations: [],
                userGroupAccesses: [],
                attributeValues: [],
                userAccesses: [],
            },
        ],
        translations: [],
        userAccesses: [],
    },
];
