export const tableAnalytics = {
  headers: [
    {
      name: 'dx',
      column: 'Data',
      valueType: 'TEXT',
      type: 'java.lang.String',
      hidden: false,
      meta: true,
    },
    {
      name: 'ou',
      column: 'Organisation unit',
      valueType: 'TEXT',
      type: 'java.lang.String',
      hidden: false,
      meta: true,
    },
    {
      name: 'pe',
      column: 'Period',
      valueType: 'TEXT',
      type: 'java.lang.String',
      hidden: false,
      meta: true,
    },
    {
      name: 'value',
      column: 'Value',
      valueType: 'NUMBER',
      type: 'java.lang.Double',
      hidden: false,
      meta: false,
    },
  ],
  metaData: {
    items: {
      '2021': { name: '2021' },
      '2022': { name: '2022' },
      NMc7zpGg9ay: {
        name: 'No of new and relapse TB cases registered, excluding cases moved to second-line treatment',
      },
      dx: { name: 'Data' },
      pe: { name: 'Period' },
      HqepvPLhqLZ: { name: 'HMIS_Form timeliness' },
      ou: { name: 'Organisation unit' },
      kyeZRGxk9g6: { name: 'HMIS Form completeness' },
      itIVeB2QV3B: { name: 'CTC Total Current on ART' },
      m0frOspS7JY: { name: 'MOH - Tanzania' },
      uGIJ6IdkP7Q: { name: 'default' },
    },
    dimensions: {
      dx: ['NMc7zpGg9ay', 'kyeZRGxk9g6', 'HqepvPLhqLZ', 'itIVeB2QV3B'],
      pe: ['2022', '2021'],
      ou: ['m0frOspS7JY'],
      co: ['uGIJ6IdkP7Q'],
    },
  },
  rows: [
    ['itIVeB2QV3B', 'm0frOspS7JY', '2021', '74925155.0'],
    ['NMc7zpGg9ay', 'm0frOspS7JY', '2021', '78854.0'],
    ['NMc7zpGg9ay', 'm0frOspS7JY', '2022', '22854.0'],
  ],
  height: 2,
  headerWidth: 4,
  width: 4,
};
