import { TableAnalytics } from '../models/table-analytics.model';

export const tableAnalytics: TableAnalytics = {
  headers: [
    {
      name: 'dx',
      column: 'Data',
      valueType: 'TEXT',
      type: 'java.lang.String',
      hidden: false,
      meta: true,
    },
    {
      name: 'pe',
      column: 'Period',
      valueType: 'TEXT',
      type: 'java.lang.String',
      hidden: false,
      meta: true,
    },
    {
      name: 'value',
      column: 'Value',
      valueType: 'NUMBER',
      type: 'java.lang.Double',
      hidden: false,
      meta: false,
    },
  ],
  metaData: {
    names: {
      '2021': '2021',
      '2022': '2022',
      pbEeSmcDhdX: 'No of child who rcvd Vit A btn 12 mnths and 5 yrs',
      dx: 'Data',
      pe: 'Period',
      ou: 'Organisation unit',
      m0frOspS7JY: 'MOH - Tanzania',
      LAST_YEAR: 'Last year',
      UDX2neHrrC3: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
      UDX2neHrrC4: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
      UDX2neHrrC5: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
      UDX2neHrrC6: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
      UDX2neHrrC7: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
    },
    items: {
      '2021': {
        uid: '2021',
        code: '2021',
        name: '2021',
        dimensionItemType: 'PERIOD',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
        startDate: '2021-01-01T00:00:00.000',
        endDate: '2021-12-31T00:00:00.000',
      },
      '2022': {
        uid: '2022',
        code: '2022',
        name: '2022',
        dimensionItemType: 'PERIOD',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
        startDate: '2022-01-01T00:00:00.000',
        endDate: '2022-12-31T00:00:00.000',
      },
      pbEeSmcDhdX: {
        uid: 'pbEeSmcDhdX',
        name: 'No of child who rcvd Vit A btn 12 mnths and 5 yrs',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      dx: {
        uid: 'dx',
        name: 'Data',
        dimensionType: 'DATA_X',
      },
      pe: {
        uid: 'pe',
        name: 'Period',
        dimensionType: 'PERIOD',
      },
      ou: {
        uid: 'ou',
        name: 'Organisation unit',
        dimensionType: 'ORGANISATION_UNIT',
      },
      m0frOspS7JY: {
        uid: 'm0frOspS7JY',
        code: 'TZ',
        name: 'MOH - Tanzania',
        dimensionItemType: 'ORGANISATION_UNIT',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      LAST_YEAR: {
        name: 'Last year',
      },
      UDX2neHrrC3: {
        uid: 'UDX2neHrrC3',
        name: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      UDX2neHrrC4: {
        uid: 'UDX2neHrrC4',
        name: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      UDX2neHrrC5: {
        uid: 'UDX2neHrrC5',
        name: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      UDX2neHrrC6: {
        uid: 'UDX2neHrrC6',
        name: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
      UDX2neHrrC7: {
        uid: 'UDX2neHrrC7',
        name: 'IPC-HMIS #waliogundulika VVU 3 -6 baada madhara',
        dimensionItemType: 'INDICATOR',
        valueType: 'NUMBER',
        totalAggregationType: 'SUM',
      },
    },
    dx: [
      'pbEeSmcDhdX',
      'UDX2neHrrC3',
      'UDX2neHrrC4',
      'UDX2neHrrC5',
      'UDX2neHrrC6',
      'UDX2neHrrC7',
    ],
    pe: ['2021', '2022'],
    ou: ['m0frOspS7JY'],
    co: [],
  },
  rows: [
    ['pbEeSmcDhdX', '2021', '15898068.0'],
    ['pbEeSmcDhdX', '2022', '3302827.0'],
    ['UDX2neHrrC3', '2021', '137.0'],
    ['UDX2neHrrC3', '2022', '4.0'],
    ['UDX2neHrrC4', '2021', '137.0'],
    ['UDX2neHrrC4', '2022', '4.0'],
    ['UDX2neHrrC5', '2021', '134.0'],
    ['UDX2neHrrC5', '2022', '137.0'],
    ['UDX2neHrrC6', '2021', '130.0'],
    ['UDX2neHrrC6', '2022', '137.0'],
    ['UDX2neHrrC7', '2021', '137.0'],
    ['UDX2neHrrC7', '2022', '137.5'],
  ],
};
