import { TableDashboardItem } from '../models/table-dashboard-item.model';

export const tableDashboardItem: TableDashboardItem = {
  lastUpdated: '2022-04-29T12:44:05.470',
  id: 'qrh6A4GAhS7',
  created: '2022-04-29T12:44:05.273',
  type: 'REPORT_TABLE',
  externalAccess: false,
  contentCount: 2,
  height: 29,
  interpretationCount: 0,
  sharing: { external: false, users: {}, userGroups: {} },
  width: 20,
  x: 0,
  y: 0,
  interpretationLikeCount: 0,
  favorite: false,
  visualization: {
    lastUpdated: '2022-05-19T00:54:15.117',
    id: 'ZrlKHBNt56p',
    created: '2022-04-29T12:42:34.378',
    name: 'EHS Indicators',
    publicAccess: '--------',
    userOrganisationUnitChildren: false,
    legendDisplayStyle: 'FILL',
    type: 'PIVOT_TABLE',
    hideEmptyColumns: false,
    subscribed: false,
    userOrganisationUnit: false,
    rowSubTotals: false,
    cumulativeValues: false,
    showDimensionLabels: false,
    sortOrder: 0,
    fontSize: 'NORMAL',
    favorite: false,
    topLimit: 0,
    userOrganisationUnitGrandChildren: false,
    displayName: 'EHS Indicators',
    percentStackedValues: false,
    noSpaceBetweenColumns: false,
    showHierarchy: false,
    hideTitle: false,
    skipRounding: false,
    showData: false,
    numberType: 'VALUE',
    hideEmptyRows: false,
    parentGraphMap: {},
    displayDensity: 'NORMAL',
    regressionType: 'NONE',
    completedOnly: false,
    colTotals: false,
    sharing: {
      owner: 'ELelSS7HfqW',
      external: false,
      users: {},
      userGroups: {},
      public: '--------',
    },
    displayFormName: 'EHS Indicators',
    hideEmptyRowItems: 'NONE',
    aggregationType: 'DEFAULT',
    hideSubtitle: false,
    hideLegend: false,
    externalAccess: false,
    legendDisplayStrategy: 'FIXED',
    colSubTotals: false,
    rowTotals: false,
    digitGroupSeparator: 'SPACE',
    regression: false,
    access: {
      read: true,
      update: true,
      externalize: true,
      delete: true,
      write: true,
      manage: true,
    },
    lastUpdatedBy: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    legendSet: {
      created: '2020-06-04T13:39:56.014',
      lastUpdated: '2022-03-04T12:07:55.303',
      name: 'Malaria positivity among Pregnance (5-100, 1-5,0-1)',
      id: 'DN4G91iSpPs',
      displayName: 'Malaria positivity among Pregnance (5-100, 1-5,0-1)',
      publicAccess: 'rw------',
      sharing: {
        owner: 'DkR8reoFU9i',
        external: false,
        users: {},
        userGroups: {},
        public: 'rw------',
      },
      externalAccess: false,
      favorite: false,
      lastUpdatedBy: {
        displayName: 'Josephat Julius',
        name: 'Josephat Julius',
        id: 'ELelSS7HfqW',
        username: 'josephatjulius',
      },
      access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
      },
      createdBy: {
        displayName: 'Tuzo Engelbert',
        name: 'Tuzo Engelbert',
        id: 'DkR8reoFU9i',
        username: 'tuzoengelbert',
      },
      user: {
        displayName: 'Tuzo Engelbert',
        name: 'Tuzo Engelbert',
        id: 'DkR8reoFU9i',
        username: 'tuzoengelbert',
      },
      favorites: [],
      userGroupAccesses: [],
      attributeValues: [],
      legends: [
        {
          lastUpdated: '2022-03-04T12:07:55.303',
          id: 'fB8PiRAiNg9',
          created: '2022-03-04T12:07:55.303',
          name: 'Excellent',
          endValue: 1.0,
          color: '#64C205',
          displayName: 'Excellent',
          externalAccess: false,
          startValue: 0.0,
          sharing: {
            external: false,
            users: {},
            userGroups: {},
          },
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          lastUpdated: '2022-03-04T12:07:55.304',
          id: 'DSpwZUlwJFP',
          created: '2022-03-04T12:07:55.304',
          name: 'Poor',
          endValue: 100.0,
          color: '#EC4205',
          displayName: 'Poor',
          externalAccess: false,
          startValue: 5.0,
          sharing: {
            external: false,
            users: {},
            userGroups: {},
          },
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
        {
          lastUpdated: '2022-03-04T12:07:55.304',
          id: 'JpS9IF2Zys5',
          created: '2022-03-04T12:07:55.304',
          name: 'Good',
          endValue: 5.0,
          color: '#F2EB1F',
          displayName: 'Good',
          externalAccess: false,
          startValue: 1.0,
          sharing: {
            external: false,
            users: {},
            userGroups: {},
          },
          favorite: false,
          access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
          },
          favorites: [],
          translations: [],
          userGroupAccesses: [],
          attributeValues: [],
          userAccesses: [],
        },
      ],
      translations: [],
      userAccesses: [],
    },
    relativePeriods: {
      thisYear: false,
      quartersLastYear: false,
      last30Days: false,
      last52Weeks: false,
      thisWeek: false,
      last90Days: false,
      last60Days: false,
      lastMonth: false,
      last14Days: false,
      biMonthsThisYear: false,
      monthsThisYear: false,
      last2SixMonths: false,
      yesterday: false,
      thisQuarter: false,
      last12Months: false,
      last5FinancialYears: false,
      thisSixMonth: false,
      lastQuarter: false,
      thisFinancialYear: false,
      last4Weeks: false,
      last3Months: false,
      thisDay: false,
      thisMonth: false,
      last5Years: false,
      last6BiMonths: false,
      last4BiWeeks: false,
      lastFinancialYear: false,
      lastBiWeek: false,
      weeksThisYear: false,
      last6Months: false,
      last3Days: false,
      quartersThisYear: false,
      monthsLastYear: false,
      lastWeek: false,
      last7Days: false,
      last180Days: false,
      thisBimonth: false,
      lastBimonth: false,
      lastSixMonth: false,
      thisBiWeek: false,
      lastYear: false,
      last12Weeks: false,
      last4Quarters: false,
    },
    createdBy: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    user: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    dataElementGroupSetDimensions: [],
    axes: [],
    attributeDimensions: [],
    translations: [],
    yearlySeries: [],
    filterDimensions: ['ou'],
    interpretations: [],
    userGroupAccesses: [],
    subscribers: [],
    optionalAxes: [],
    columns: [],
    dataElementDimensions: [],
    periods: [
      {
        id: '2021',
      },
      {
        id: '2022',
      },
    ],
    categoryDimensions: [],
    rowDimensions: ['dx'],
    series: [],
    itemOrganisationUnitGroups: [],
    programIndicatorDimensions: [],
    attributeValues: [],
    columnDimensions: ['pe'],
    userAccesses: [],
    favorites: [],
    dataDimensionItems: [
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: {
          id: 'HqepvPLhqLZ',
        },
      },
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: {
          id: 'kyeZRGxk9g6',
        },
      },
      {
        dataDimensionItemType: 'DATA_ELEMENT',
        dataElement: {
          id: 'NMc7zpGg9ay',
        },
      },
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: {
          id: 'itIVeB2QV3B',
        },
      },
    ],
    categoryOptionGroupSetDimensions: [],
    organisationUnitGroupSetDimensions: [],
    organisationUnitLevels: [],
    organisationUnits: [
      {
        id: 'm0frOspS7JY',
      },
    ],
    filters: [],
    rows: [],
  },
  access: {
    read: true,
    update: true,
    externalize: true,
    delete: true,
    write: true,
    manage: true,
  },
  reportTable: {
    lastUpdated: '2022-05-19T00:54:15.117',
    id: 'ZrlKHBNt56p',
    created: '2022-04-29T12:42:34.378',
    name: 'EHS Indicators',
    numberType: 'VALUE',
    publicAccess: '--------',
    userOrganisationUnitChildren: false,
    legendDisplayStyle: 'FILL',
    hideEmptyColumns: false,
    subscribed: false,
    hideEmptyRows: false,
    parentGraphMap: {},
    userOrganisationUnit: false,
    rowSubTotals: false,
    displayDensity: 'NORMAL',
    completedOnly: false,
    sharing: {
      owner: 'ELelSS7HfqW',
      external: false,
      users: {},
      userGroups: {},
      public: '--------',
    },
    colTotals: false,
    displayFormName: 'EHS Indicators',
    showDimensionLabels: false,
    sortOrder: 0,
    fontSize: 'NORMAL',
    favorite: false,
    topLimit: 0,
    aggregationType: 'DEFAULT',
    userOrganisationUnitGrandChildren: false,
    displayName: 'EHS Indicators',
    hideSubtitle: false,
    externalAccess: false,
    legendDisplayStrategy: 'FIXED',
    colSubTotals: false,
    showHierarchy: false,
    rowTotals: false,
    cumulative: false,
    digitGroupSeparator: 'SPACE',
    hideTitle: false,
    regression: false,
    skipRounding: false,
    lastUpdatedBy: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    access: {
      read: true,
      update: true,
      externalize: true,
      delete: true,
      write: true,
      manage: true,
    },
    relativePeriods: {
      thisYear: false,
      quartersLastYear: false,
      last30Days: false,
      last52Weeks: false,
      thisWeek: false,
      last90Days: false,
      last60Days: false,
      lastMonth: false,
      last14Days: false,
      biMonthsThisYear: false,
      monthsThisYear: false,
      last2SixMonths: false,
      yesterday: false,
      thisQuarter: false,
      last12Months: false,
      last5FinancialYears: false,
      thisSixMonth: false,
      lastQuarter: false,
      thisFinancialYear: false,
      last4Weeks: false,
      last3Months: false,
      thisDay: false,
      thisMonth: false,
      last5Years: false,
      last6BiMonths: false,
      last4BiWeeks: false,
      lastFinancialYear: false,
      lastBiWeek: false,
      weeksThisYear: false,
      last6Months: false,
      last3Days: false,
      quartersThisYear: false,
      monthsLastYear: false,
      lastWeek: false,
      last7Days: false,
      last180Days: false,
      thisBimonth: false,
      lastBimonth: false,
      lastSixMonth: false,
      thisBiWeek: false,
      lastYear: false,
      last12Weeks: false,
      last4Quarters: false,
    },
    createdBy: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    user: {
      displayName: 'Josephat Julius',
      name: 'Josephat Julius',
      id: 'ELelSS7HfqW',
      username: 'josephatjulius',
    },
    dataElementGroupSetDimensions: [],
    attributeDimensions: [],
    translations: [],
    filterDimensions: ['ou'],
    interpretations: [],
    itemOrganisationUnitGroups: [],
    userGroupAccesses: [],
    programIndicatorDimensions: [],
    subscribers: [],
    attributeValues: [],
    columnDimensions: ['pe'],
    userAccesses: [],
    favorites: [],
    dataDimensionItems: [
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: { id: 'HqepvPLhqLZ' },
      },
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: { id: 'kyeZRGxk9g6' },
      },
      {
        dataDimensionItemType: 'DATA_ELEMENT',
        dataElement: { id: 'NMc7zpGg9ay' },
      },
      {
        dataDimensionItemType: 'INDICATOR',
        indicator: { id: 'itIVeB2QV3B' },
      },
    ],
    categoryOptionGroupSetDimensions: [],
    columns: [],
    organisationUnitGroupSetDimensions: [],
    organisationUnitLevels: [],
    dataElementDimensions: [],
    periods: [{ id: '2021' }, { id: '2022' }],
    organisationUnits: [{ id: 'm0frOspS7JY' }],
    categoryDimensions: [],
    filters: [],
    rows: [],
    rowDimensions: ['dx'],
  },
  favorites: [],
  reports: [],
  translations: [],
  userGroupAccesses: [],
  attributeValues: [],
  resources: [],
  users: [],
  userAccesses: [],
};
