import { MapDashboardItem } from '../models/map-dashboard-item.model';

export const mapDashboardItemConfig: MapDashboardItem = {
  lastUpdated: '2022-05-25T12:45:38.301',
  id: 'z7esbfS38Fv',
  created: '2022-05-25T12:45:37.764',
  type: 'MAP',
  externalAccess: false,
  contentCount: 1,
  height: 30,
  interpretationCount: 0,
  sharing: {
    external: false,
    users: {},
    userGroups: {},
  },
  width: 29,
  x: 0,
  y: 0,
  interpretationLikeCount: 0,
  favorite: false,
  access: {
    read: true,
    update: true,
    externalize: true,
    delete: true,
    write: true,
    manage: true,
  },
  map: {
    lastUpdated: '2022-05-25T12:43:36.657',
    id: 'ndcadmm8uQW',
    created: '2020-06-04T15:22:39.245',
    name: 'DTP_HepB_Hib_1 to  DTP_HepB_Hib_3 Dropout rates',
    displayName: 'DTP_HepB_Hib_1 to  DTP_HepB_Hib_3 Dropout rates',
    basemap: 'osmLight',
    externalAccess: false,
    subscribed: false,
    sharing: {
      owner: 'DkR8reoFU9i',
      external: false,
      users: {},
      userGroups: {},
    },
    displayFormName: 'DTP_HepB_Hib_1 to  DTP_HepB_Hib_3 Dropout rates',
    favorite: false,
    access: {
      read: true,
      update: true,
      externalize: true,
      delete: true,
      write: true,
      manage: true,
    },
    lastUpdatedBy: {
      displayName: 'Walter V. Faustine',
      name: 'Walter V. Faustine',
      id: 'PKUlOGYBc0u',
      username: 'waltervfaustine',
    },
    createdBy: {
      displayName: 'Tuzo Engelbert',
      name: 'Tuzo Engelbert',
      id: 'DkR8reoFU9i',
      username: 'tuzoengelbert',
    },
    user: {
      displayName: 'Tuzo Engelbert',
      name: 'Tuzo Engelbert',
      id: 'DkR8reoFU9i',
      username: 'tuzoengelbert',
    },
    favorites: [],
    translations: [],
    mapViews: [
      {
        lastUpdated: '2022-05-25T12:43:36.650',
        id: 'cbSiRmNJihM',
        created: '2022-05-25T12:41:38.541',
        name: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        userOrganisationUnitChildren: false,
        subscribed: false,
        userOrganisationUnit: false,
        method: 1,
        renderingStrategy: 'SINGLE',
        sortOrder: 0,
        favorite: false,
        topLimit: 0,
        userOrganisationUnitGrandChildren: false,
        displayName: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        layer: 'thematic',
        hideTitle: false,
        eventClustering: false,
        opacity: 0.9,
        parentLevel: 0,
        parentGraphMap: {},
        completedOnly: false,
        eventPointRadius: 0,
        sharing: {
          external: false,
          users: {},
          userGroups: {},
        },
        displayFormName: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        thematicMapType: 'CH',
        hideSubtitle: false,
        externalAccess: false,
        digitGroupSeparator: 'SPACE',
        access: {
          read: true,
          update: true,
          externalize: true,
          delete: true,
          write: true,
          manage: true,
        },
        relativePeriods: {
          thisYear: false,
          quartersLastYear: false,
          last30Days: false,
          last52Weeks: false,
          thisWeek: false,
          last90Days: false,
          last60Days: false,
          lastMonth: false,
          last14Days: false,
          biMonthsThisYear: false,
          monthsThisYear: false,
          last2SixMonths: false,
          yesterday: false,
          thisQuarter: false,
          last12Months: false,
          last5FinancialYears: false,
          thisSixMonth: false,
          lastQuarter: true,
          thisFinancialYear: false,
          last4Weeks: false,
          last3Months: false,
          thisDay: false,
          thisMonth: false,
          last5Years: false,
          last6BiMonths: false,
          last4BiWeeks: false,
          lastFinancialYear: false,
          lastBiWeek: false,
          weeksThisYear: false,
          last6Months: false,
          last3Days: false,
          quartersThisYear: false,
          monthsLastYear: false,
          lastWeek: false,
          last7Days: false,
          last180Days: false,
          thisBimonth: false,
          lastBimonth: false,
          lastSixMonth: false,
          thisBiWeek: false,
          lastYear: false,
          last12Weeks: false,
          last4Quarters: false,
        },
        legendSet: {
          id: 'HpqwUDvTbJT',
        },
        dataElementGroupSetDimensions: [],
        attributeDimensions: [],
        translations: [],
        filterDimensions: ['pe'],
        interpretations: [],
        userGroupAccesses: [],
        subscribers: [],
        columns: [],
        dataElementDimensions: [],
        periods: [],
        categoryDimensions: [],
        itemOrganisationUnitGroups: [],
        programIndicatorDimensions: [],
        attributeValues: [],
        columnDimensions: ['dx'],
        userAccesses: [],
        favorites: [],
        dataDimensionItems: [
          {
            dataDimensionItemType: 'INDICATOR',
            indicator: {
              id: 'IgrF8Dxamd0',
            },
          },
        ],
        categoryOptionGroupSetDimensions: [],
        organisationUnitGroupSetDimensions: [],
        organisationUnitLevels: [2],
        organisationUnits: [],
        filters: [],
        rows: [],
      },
      {
        lastUpdated: '2022-05-25T12:43:36.650',
        id: 'JHLoK5HUbcH',
        created: '2020-06-04T15:22:39.243',
        name: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        userOrganisationUnitChildren: true,
        subscribed: false,
        userOrganisationUnit: true,
        method: 1,
        renderingStrategy: 'SINGLE',
        sortOrder: 0,
        favorite: false,
        topLimit: 0,
        userOrganisationUnitGrandChildren: false,
        displayName: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        layer: 'thematic',
        hideTitle: false,
        eventClustering: false,
        opacity: 0.8,
        parentLevel: 0,
        parentGraphMap: {},
        completedOnly: false,
        eventPointRadius: 0,
        sharing: {
          external: false,
          users: {},
          userGroups: {},
        },
        displayFormName: 'Penta 1 TO 3 Dropout Rate Inside Service Area',
        thematicMapType: 'CHOROPLETH',
        hideSubtitle: false,
        externalAccess: false,
        digitGroupSeparator: 'SPACE',
        access: {
          read: true,
          update: true,
          externalize: true,
          delete: true,
          write: true,
          manage: true,
        },
        relativePeriods: {
          thisYear: false,
          quartersLastYear: false,
          last30Days: false,
          last52Weeks: false,
          thisWeek: false,
          last90Days: false,
          last60Days: false,
          lastMonth: false,
          last14Days: false,
          biMonthsThisYear: false,
          monthsThisYear: false,
          last2SixMonths: false,
          yesterday: false,
          thisQuarter: false,
          last12Months: false,
          last5FinancialYears: false,
          thisSixMonth: false,
          lastQuarter: true,
          thisFinancialYear: false,
          last4Weeks: false,
          last3Months: false,
          thisDay: false,
          thisMonth: false,
          last5Years: false,
          last6BiMonths: false,
          last4BiWeeks: false,
          lastFinancialYear: false,
          lastBiWeek: false,
          weeksThisYear: false,
          last6Months: false,
          last3Days: false,
          quartersThisYear: false,
          monthsLastYear: false,
          lastWeek: false,
          last7Days: false,
          last180Days: false,
          thisBimonth: false,
          lastBimonth: false,
          lastSixMonth: false,
          thisBiWeek: false,
          lastYear: false,
          last12Weeks: false,
          last4Quarters: false,
        },
        legendSet: {
          id: 'RVJUoXd7DOH',
        },
        dataElementGroupSetDimensions: [],
        attributeDimensions: [],
        translations: [],
        filterDimensions: ['pe'],
        interpretations: [],
        userGroupAccesses: [],
        subscribers: [],
        columns: [],
        dataElementDimensions: [],
        periods: [],
        categoryDimensions: [],
        itemOrganisationUnitGroups: [],
        programIndicatorDimensions: [],
        attributeValues: [],
        columnDimensions: ['dx'],
        userAccesses: [],
        favorites: [],
        dataDimensionItems: [
          {
            dataDimensionItemType: 'INDICATOR',
            indicator: {
              id: 'IgrF8Dxamd0',
            },
          },
        ],
        categoryOptionGroupSetDimensions: [],
        organisationUnitGroupSetDimensions: [],
        organisationUnitLevels: [],
        organisationUnits: [],
        filters: [],
        rows: [],
      },
    ],
    interpretations: [],
    userGroupAccesses: [],
    subscribers: [],
    attributeValues: [],
    userAccesses: [],
  },
  favorites: [],
  reports: [],
  translations: [],
  userGroupAccesses: [],
  attributeValues: [],
  resources: [],
  users: [],
  userAccesses: [],
};
