import { LegendSet } from "packages/d2-visualizer/src/lib/modules/map/models/legend-set.model";

export const demoLegendSet: LegendSet = {
    created: '2020-06-04T11:57:02.258',
    lastUpdated: '2022-03-04T12:07:20.914',
    name: 'Malaria opd ratio (0-0.4,0.4-0.6,0.6-1)',
    href: 'https://dhis.moh.go.tz/api/36/legendSets/tGxjpAHEnVa',
    id: 'tGxjpAHEnVa',
    displayName: 'Malaria opd ratio (0-0.4,0.4-0.6,0.6-1)',
    publicAccess: 'rw------',
    sharing: {
        owner: 'DkR8reoFU9i',
        external: false,
        users: {},
        userGroups: {},
        public: 'rw------',
    },
    externalAccess: false,
    favorite: false,
    lastUpdatedBy: {
        displayName: 'Josephat Julius',
        name: 'Josephat Julius',
        id: 'ELelSS7HfqW',
        username: 'josephatjulius',
    },
    access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
    },
    createdBy: {
        displayName: 'Tuzo Engelbert',
        name: 'Tuzo Engelbert',
        id: 'DkR8reoFU9i',
        username: 'tuzoengelbert',
    },
    user: {
        displayName: 'Tuzo Engelbert',
        name: 'Tuzo Engelbert',
        id: 'DkR8reoFU9i',
        username: 'tuzoengelbert',
    },
    favorites: [],
    userGroupAccesses: [],
    attributeValues: [],
    legends: [
        {
            lastUpdated: '2022-03-04T12:07:20.914',
            id: 'dNOveczZY4A',
            created: '2022-03-04T12:07:20.914',
            name: 'Poor',
            endValue: 0.4,
            color: '#CD061D',
            displayName: 'Poor',
            externalAccess: false,
            startValue: 0.0,
            sharing: {
                external: false,
                users: {},
                userGroups: {},
            },
            favorite: false,
            access: {
                read: true,
                update: true,
                externalize: true,
                delete: true,
                write: true,
                manage: true,
            },
            favorites: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            userAccesses: [],
        },
        {
            lastUpdated: '2022-03-04T12:07:20.914',
            id: 'JLf51mqLiLS',
            created: '2022-03-04T12:07:20.914',
            name: 'Excellent',
            endValue: 1.0,
            color: '#4C9B0E',
            displayName: 'Excellent',
            externalAccess: false,
            startValue: 0.6,
            sharing: {
                external: false,
                users: {},
                userGroups: {},
            },
            favorite: false,
            access: {
                read: true,
                update: true,
                externalize: true,
                delete: true,
                write: true,
                manage: true,
            },
            favorites: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            userAccesses: [],
        },
        {
            lastUpdated: '2022-03-04T12:07:20.914',
            id: 'ssrfhvzLFNI',
            created: '2022-03-04T12:07:20.914',
            name: 'Good',
            endValue: 0.6,
            color: '#EDE722',
            displayName: 'Good',
            externalAccess: false,
            startValue: 0.4,
            sharing: {
                external: false,
                users: {},
                userGroups: {},
            },
            favorite: false,
            access: {
                read: true,
                update: true,
                externalize: true,
                delete: true,
                write: true,
                manage: true,
            },
            favorites: [],
            translations: [],
            userGroupAccesses: [],
            attributeValues: [],
            userAccesses: [],
        },
    ],
    translations: [],
    userAccesses: [],
};
