import { MapDashboardItem } from '../../models/map-dashboard-item.model';

export const facilityDashboardItemConfig: MapDashboardItem = {
    lastUpdated: '2022-08-09T16:42:43.292',
    id: 'KsR0Eki7H45',
    created: '2022-08-09T16:42:42.979',
    type: 'MAP',
    externalAccess: false,
    contentCount: 1,
    height: 26,
    interpretationCount: 0,
    sharing: {
        external: false,
        users: {},
        userGroups: {},
    },
    width: 32,
    x: 0,
    y: 0,
    interpretationLikeCount: 0,
    favorite: false,
    access: {
        read: true,
        update: true,
        externalize: true,
        delete: true,
        write: true,
        manage: true,
    },
    map: {
        lastUpdated: '2022-08-09T16:41:31.930',
        id: 'p5nkBxX7jMt',
        created: '2022-08-09T16:41:31.930',
        name: 'Facility Map Demo',
        displayName: 'Facility Map Demo',
        publicAccess: 'rw------',
        basemap: 'osmLight',
        description: 'Facility Map Demo',
        externalAccess: false,
        subscribed: false,
        displayDescription: 'Facility Map Demo',
        sharing: {
            owner: 'PKUlOGYBc0u',
            external: false,
            users: {},
            userGroups: {},
            public: 'rw------',
        },
        displayFormName: 'Facility Map Demo',
        favorite: false,
        access: {
            read: true,
            update: true,
            externalize: true,
            delete: true,
            write: true,
            manage: true,
        },
        lastUpdatedBy: {
            displayName: 'Walter V. Faustine',
            name: 'Walter V. Faustine',
            id: 'PKUlOGYBc0u',
            username: 'waltervfaustine',
        },
        createdBy: {
            displayName: 'Walter V. Faustine',
            name: 'Walter V. Faustine',
            id: 'PKUlOGYBc0u',
            username: 'waltervfaustine',
        },
        user: {
            displayName: 'Walter V. Faustine',
            name: 'Walter V. Faustine',
            id: 'PKUlOGYBc0u',
            username: 'waltervfaustine',
        },
        favorites: [],
        translations: [],
        mapViews: [
            {
                lastUpdated: '2022-08-09T16:41:31.938',
                id: 'oIvf7My9h6e',
                created: '2022-08-09T16:41:30.451',
                name: 'oIvf7My9h6e',
                userOrganisationUnitChildren: false,
                subscribed: false,
                userOrganisationUnit: false,
                renderingStrategy: 'SINGLE',
                labels: true,
                sortOrder: 0,
                favorite: false,
                topLimit: 0,
                userOrganisationUnitGrandChildren: false,
                displayName: 'oIvf7My9h6e',
                layer: 'facility',
                hideTitle: false,
                eventClustering: false,
                opacity: 1.0,
                parentLevel: 0,
                parentGraphMap: {},
                completedOnly: false,
                eventPointRadius: 0,
                sharing: {
                    external: false,
                    users: {},
                    userGroups: {},
                },
                displayFormName: 'oIvf7My9h6e',
                hideSubtitle: false,
                externalAccess: false,
                digitGroupSeparator: 'SPACE',
                access: {
                    read: true,
                    update: true,
                    externalize: true,
                    delete: true,
                    write: true,
                    manage: true,
                },
                organisationUnitGroupSet: {
                    id: 'IymWT9V0HZI',
                },
                dataElementGroupSetDimensions: [],
                attributeDimensions: [],
                translations: [],
                filterDimensions: [],
                interpretations: [],
                userGroupAccesses: [],
                subscribers: [],
                columns: [],
                dataElementDimensions: [],
                periods: [],
                categoryDimensions: [],
                itemOrganisationUnitGroups: [],
                programIndicatorDimensions: [],
                attributeValues: [],
                columnDimensions: [],
                userAccesses: [],
                favorites: [],
                dataDimensionItems: [],
                categoryOptionGroupSetDimensions: [],
                organisationUnitGroupSetDimensions: [],
                organisationUnitLevels: [4],
                organisationUnits: [
                    {
                        id: 'm0frOspS7JY',
                    },
                ],
                filters: [],
                rows: [],
            },
        ],
        interpretations: [],
        userGroupAccesses: [],
        subscribers: [],
        attributeValues: [],
        userAccesses: [],
    },
    favorites: [],
    reports: [],
    translations: [],
    userGroupAccesses: [],
    attributeValues: [],
    resources: [],
    users: [],
    userAccesses: [],
};
