import { LegendSet } from '../models/legend-set.model';
import { TableAnalytics } from '../models/table-analytics.model';

export const tableLegendSets: LegendSet[] = [
  {
    id: 'c9JmK1NjfRP',
    name: 'Malaria deaths legend (10-100,5-10, 5-0)',
    legends: [
      {
        id: 'ZBqibVHzH9y',
        endValue: 5,
        color: '#2D8851',
        name: '0 - 5',
        startValue: 0,
      },
      {
        id: 'p9V4g6kyVgb',
        endValue: 10,
        color: '#EDE722',
        name: '5 - 10',
        startValue: 5,
      },
      {
        id: 'iDOUOWXI0yB',
        endValue: 100,
        color: '#f03b20',
        name: '10 - 100',
        startValue: 10,
      },
    ],
  },
  {
    id: 'kno6QxxQM5J',
    name: 'ANC Positivity rate (<1, 1-2 and >2)',
    legends: [
      {
        id: 'C3l7N0FF3jn',
        endValue: 2,
        color: '#FFFF00',
        name: 'Medium',
        startValue: 1,
      },
      {
        id: 'wGUE0yfzrbl',
        endValue: 100,
        color: '#FF0000',
        name: 'High',
        startValue: 2,
      },
      {
        id: 'X6SxLIu61e3',
        endValue: 1,
        color: '#00B050',
        name: 'Low',
        startValue: 0,
      },
    ],
  },
  {
    id: 'OzO2OjPso4P',
    name: 'ANC coverage (<20, 20-40 and > 40)',
    legends: [
      {
        id: 'uT5MPVNSbuk',
        endValue: 20,
        color: '#FF0000',
        name: 'Low',
        startValue: 0,
      },
      {
        id: 'Grwek0Kk4vu',
        endValue: 40,
        color: '#FFFF00',
        name: 'Medium',
        startValue: 20,
      },
      {
        id: 'INrebmMr5gr',
        endValue: 100,
        color: '#00B050',
        name: 'High',
        startValue: 40,
      },
    ],
  },
  {
    id: 'sjYF2oeQTCv',
    name: 'Age groups (0-1, 1-5,5-60,60+)',
    legends: [
      {
        id: 'llxA72cgcx1',
        endValue: 100,
        color: '#E1E1E1',
        name: '60+',
        startValue: 60,
      },
      {
        id: 'drCBvizgcZb',
        endValue: 5,
        color: '#E1E1E1',
        name: '1-5',
        startValue: 1,
      },
      {
        id: 'KW3leLIi7rv',
        endValue: 1,
        color: '#E1E1E1',
        name: '0-1',
        startValue: 0,
      },
      {
        id: 'wPdNlx9Ia8i',
        endValue: 60,
        color: '#E1E1E1',
        name: '5-60',
        startValue: 5,
      },
    ],
  },
  {
    id: 'tiZgtVlGhiE',
    name: 'Age groups 0-5,5+',
    legends: [
      {
        id: 'rC4bHKw3mnz',
        endValue: 120,
        color: '#FFA500',
        name: '5+',
        startValue: 5,
      },
      {
        id: 'yAm6ewR8NVw',
        endValue: 5,
        color: '#FFA500',
        name: '0-5',
        startValue: 0,
      },
    ],
  },
  {
    id: 'xBiYjbsJGzP',
    name: 'Annual Parasite Incidence (0-1,1-5,5-30,30-100)',
    legends: [
      {
        id: 'RBvqPn3MrLW',
        endValue: 5,
        color: '#DCF5B5',
        name: '1- < 5',
        startValue: 1,
      },
      {
        id: 'ZGcHZ1cAirl',
        endValue: 1,
        color: '#10940F',
        name: '<1',
        startValue: 0,
      },
      {
        id: 'SV8KZw14FoR',
        endValue: 30,
        color: '#E3EC15',
        name: '5 - < 30',
        startValue: 5,
      },
      {
        id: 'JSXn0M7OGFk',
        endValue: 100,
        color: '#D5280B',
        name: '>= 30',
        startValue: 30,
      },
    ],
  },
  {
    id: 'Y9JrIOBG4KD',
    name: 'Annual blood examination rate (0-15,15-75,75-150,150-500)',
    legends: [
      {
        id: 'L5DbzMhf4X7',
        endValue: 150,
        color: '#F5F50C',
        name: '75 - < 150',
        startValue: 75,
      },
      {
        id: 'Ugiyj6PbaVr',
        endValue: 15,
        color: '#328129',
        name: '<15',
        startValue: 0,
      },
      {
        id: 'hVCLvZdY7QD',
        endValue: 500,
        color: '#F02213',
        name: '>= 150',
        startValue: 150,
      },
      {
        id: 'eGFz94RjoRU',
        endValue: 75,
        color: '#C1E6DC',
        name: '15 - < 75',
        startValue: 15,
      },
    ],
  },
  {
    id: 'Fg0ZFnXf9XF',
    name: 'Available Yes-No',
    legends: [],
  },
  {
    id: 'tDS0kjr7t0u',
    name: 'Coverages ANC / Immunization (0-70,70-80,80-90,90-100, >100)',
    legends: [
      {
        id: 'IJ5n22EayFC',
        endValue: 70,
        color: '#F83232',
        name: 'Low',
        startValue: 0,
      },
      {
        id: 'oewEd8NQyxE',
        endValue: 1000,
        color: '#C0C0C0',
        name: 'Uncertain',
        startValue: 100,
      },
      {
        id: 'RcO7meU0dzs',
        endValue: 90,
        color: '#97FA97',
        name: 'High',
        startValue: 80,
      },
      {
        id: 'OsjVYXRoocQ',
        endValue: 100,
        color: '#0DAA30',
        name: 'Very high',
        startValue: 90,
      },
      {
        id: 'pWMRD9FvW89',
        endValue: 80,
        color: '#FAAC1C',
        name: 'Medium',
        startValue: 70,
      },
    ],
  },
  {
    id: 'HpqwUDvTbJT',
    name: 'Drop out rates (-100-0, 0-10, 10-100)',
    legends: [
      {
        id: 'S3jgoE3JSQY',
        endValue: 10,
        color: '#0CFA19',
        name: '0 - 10',
        startValue: 0,
      },
      {
        id: 'QqOUuAGWQJg',
        endValue: 0,
        color: '#FFFFFF',
        name: '-100 - 0',
        startValue: -100,
      },
      {
        id: 'm9hkjaFdfJn',
        endValue: 100,
        color: '#F60404',
        name: '10 - 100',
        startValue: 10,
      },
    ],
  },
  {
    id: 'dhUoY4e047S',
    name: 'Example Map (0-50,50-75, 75-100)',
    legends: [
      {
        id: 'zSg8hJPQnrP',
        endValue: 50,
        color: '#FF0000',
        name: 'Low',
        startValue: 0,
      },
      {
        id: 'O3Avu6Kripy',
        endValue: 75,
        color: '#FFFF00',
        name: 'Medium',
        startValue: 50,
      },
      {
        id: 'PpyPJzdAkIK',
        endValue: 100,
        color: '#008000',
        name: 'High',
        startValue: 75,
      },
    ],
  },
  {
    id: 'LDisjuXxJ0z',
    name: 'HMIS Legend (0-50,50-80,80-150)',
    legends: [
      {
        id: 'bN1jMhT6IX7',
        endValue: 80,
        color: '#DCFF00',
        name: 'Medium',
        startValue: 50,
      },
      {
        id: 'uLeHebQqO4z',
        endValue: 150,
        color: '#00FF24',
        name: 'High',
        startValue: 80,
      },
      {
        id: 'mZjMwaPah85',
        endValue: 50,
        color: '#F90307',
        name: 'Low',
        startValue: 0,
      },
    ],
  },
  {
    id: 'xIiEe1otOXk',
    name: 'HPS Health education (0-40, 40-80, 80-100)',
    legends: [
      {
        id: 'bcbyAW9eDRU',
        endValue: 100,
        color: '#55BF3B',
        name: '80 - 100',
        startValue: 80,
      },
      {
        id: 'CC1X2Sx2PSA',
        endValue: 80,
        color: '#FFE425',
        name: '40 - 80',
        startValue: 40,
      },
      {
        id: 'uTKTZH9TcEw',
        endValue: 40,
        color: '#E92C2C',
        name: '0 - 40',
        startValue: 0,
      },
    ],
  },
  {
    id: 'Fd4AudxPCkf',
    name: 'IPTp3 outliers > 1,000 (1000-5000,5000-1000000)',
    legends: [
      {
        id: 'udsSqZAxTyJ',
        endValue: 1000000,
        color: '#C900FF',
        name: '',
        startValue: 5000,
      },
      {
        id: 'WSouaun5kji',
        endValue: 5000,
        color: '#00D9FF',
        name: '',
        startValue: 1000,
      },
    ],
  },
  {
    id: 'RsAqN10uPVB',
    name: 'Immunisation (0-50,50-75,75-90,90-140,140-500)',
    legends: [
      {
        id: 'pZGsEJUIkjr',
        endValue: 50,
        color: '#FD3406',
        name: 'Red',
        startValue: 0,
      },
      {
        id: 'UxBNE2gQ3R0',
        endValue: 75,
        color: '#F39276',
        name: 'Light Red',
        startValue: 50,
      },
      {
        id: 'kUl7IMPud6u',
        endValue: 90,
        color: '#B5F5A4',
        name: 'Light Green',
        startValue: 75,
      },
      {
        id: 'Tfn7DI21yby',
        endValue: 140,
        color: '#369A06',
        name: 'Green',
        startValue: 90,
      },
      {
        id: 'taztE3WBxJy',
        endValue: 500,
        color: '#0753B9',
        name: 'Blue(Too High coverage)',
        startValue: 140,
      },
    ],
  },
  {
    id: 'U8uqywQDwf9',
    name: 'LLIN Missed Clients',
    legends: [
      {
        id: 'Xj8YxPjed5b',
        endValue: -5,
        color: '#FFFF00',
        name: 'satisfactory',
        startValue: -19,
      },
      {
        id: 'nYCg1W2twjy',
        endValue: 19,
        color: '#FFFF00',
        name: 'satisfactory',
        startValue: 5,
      },
      {
        id: 'ROUxwQcktyu',
        endValue: -19,
        color: '#FE0F00',
        name: 'Higher',
        startValue: -1000000000,
      },
      {
        id: 'iQyQB1Xl6vs',
        endValue: 0,
        color: '#0DBD00',
        name: 'Low or No',
        startValue: -5,
      },
      {
        id: 'INQh2JMxfu9',
        endValue: 5,
        color: '#0DBD00',
        name: 'Low or No',
        startValue: 0,
      },
      {
        id: 'CR45OFpkDdm',
        endValue: 1000000000,
        color: '#FE0F00',
        name: 'Higer',
        startValue: 19,
      },
    ],
  },
  {
    id: 'Lz8GWEDyrDe',
    name: 'LLIN Month of Stock (-10000-0.001,0.001-2,2-4.001,4.001-1000000)',
    legends: [
      {
        id: 'mK8P196ZZ40',
        endValue: 4.001,
        color: '#81BB7B',
        name: 'Adequately Stocked',
        startValue: 2,
      },
      {
        id: 'XNm6WZtAWGR',
        endValue: 2,
        color: '#FBFB65',
        name: 'Under Stocked',
        startValue: 0.001,
      },
      {
        id: 'w1HHMk0nK2Y',
        endValue: 1000000,
        color: '#4C65E6',
        name: 'Overstocked',
        startValue: 4.001,
      },
      {
        id: 'pzuzAnMwW8E',
        endValue: 0.001,
        color: '#F95E5D',
        name: 'Stocked Out',
        startValue: -10000,
      },
    ],
  },
  {
    id: 'Mq8xKVO5Uis',
    name: 'Large PCV 3 outliers (0-300,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'YC2RU54r28I',
        endValue: 300,
        color: 'TRANSPARENT',
        name: 'No large outliers',
        startValue: 0,
      },
      {
        id: 'ZGfOV76q3gx',
        endValue: 5000,
        color: '#6B7E97',
        name: '1,000 to 5,000',
        startValue: 1000,
      },
      {
        id: 'h281tyMkuqM',
        endValue: 1000,
        color: '#BECBE3',
        name: '300 to 1,000',
        startValue: 300,
      },
      {
        id: 'ldOK8O3U47T',
        endValue: 1000000,
        color: '#1C2C4C',
        name: '> 5,000',
        startValue: 5000,
      },
    ],
  },
  {
    id: 'Hfn9mvqBT4C',
    name: 'MAP - IPTp2 coverage (0-20,20-40,40-60,60-80,80-100)',
    legends: [
      {
        id: 'enmwxGNNMek',
        endValue: 40,
        color: '#fecc5c',
        name: '20 - 40',
        startValue: 20,
      },
      {
        id: 'LozoQmuAq6I',
        endValue: 100,
        color: '#bd0026',
        name: '80 - 100',
        startValue: 80,
      },
      {
        id: 'cNHpYOb3b7l',
        endValue: 60,
        color: '#fd8d3c',
        name: '40 - 60',
        startValue: 40,
      },
      {
        id: 'gPjibd3qW5V',
        endValue: 80,
        color: '#f03b20',
        name: '60 - 80',
        startValue: 60,
      },
      {
        id: 'xhbGxJ6X6Mj',
        endValue: 20,
        color: '#ffffb2',
        name: '0 - 20',
        startValue: 0,
      },
    ],
  },
  {
    id: 'Va5lLKqSnyN',
    name: 'MAP -BS positivity rate (0-50,50-75,75-100)',
    legends: [
      {
        id: 'DpGb1HcIO6K',
        endValue: 50,
        color: '#ffeda0',
        name: '0 - 50',
        startValue: 0,
      },
      {
        id: 'ECS2k1vzWwT',
        endValue: 100,
        color: '#f03b20',
        name: '75 - 100',
        startValue: 75,
      },
      {
        id: 'Xpa57PX2CBc',
        endValue: 75,
        color: '#feb24c',
        name: '50 - 75',
        startValue: 50,
      },
    ],
  },
  {
    id: 'q7gG3cr5I8r',
    name: 'MSDQI scorecard (-1-50,50-75,75-101)',
    legends: [
      {
        id: 'Vxf59qln4BR',
        endValue: 101,
        color: '#3D7312',
        name: '75 - 100',
        startValue: 75,
      },
      {
        id: 'XteGn7RpcIB',
        endValue: 50,
        color: '#E92C2C',
        name: '0 - 50',
        startValue: -1,
      },
      {
        id: 'OFo1zlxpBbb',
        endValue: 75,
        color: '#FFE425',
        name: '50 - 75',
        startValue: 50,
      },
    ],
  },
  {
    id: 'c7vminJqAQL',
    name: 'MSDQI scores legend (0-50,50-75,75-100)',
    legends: [
      {
        id: 'H4sthFC2gK1',
        endValue: 50,
        color: '#FF003B',
        name: '0 - 50',
        startValue: 0,
      },
      {
        id: 'ue5IkebzCTr',
        endValue: 100,
        color: '#109A34',
        name: '75 - 100',
        startValue: 75,
      },
      {
        id: 'AZnZzZZgUix',
        endValue: 75,
        color: '#FFED58',
        name: '50 - 75',
        startValue: 50,
      },
    ],
  },
  {
    id: 'TkhNaZccYKX',
    name: 'Malaria Incidence (0-50,50-100,100-150,150-200,200-500)',
    legends: [
      {
        id: 'PO95Cn0oLPK',
        endValue: 100,
        color: '#AAFB07',
        name: '50-<100',
        startValue: 50,
      },
      {
        id: 'T9aNgSZ9mWv',
        endValue: 50,
        color: '#1F4703',
        name: '<50',
        startValue: 0,
      },
      {
        id: 'TDxdtBoYzcu',
        endValue: 500,
        color: '#F1220B',
        name: '>200',
        startValue: 200,
      },
      {
        id: 'RuRXzLBt3Yl',
        endValue: 150,
        color: '#F2E807',
        name: '100-<150',
        startValue: 100,
      },
      {
        id: 'EW7VzTd0yMo',
        endValue: 200,
        color: '#FFA900',
        name: '150-<200',
        startValue: 150,
      },
    ],
  },
  {
    id: 'tGxjpAHEnVa',
    name: 'Malaria opd ratio (0-0.4,0.4-0.6,0.6-1)',
    legends: [
      {
        id: 'JLf51mqLiLS',
        endValue: 1,
        color: '#4C9B0E',
        name: 'Excellent',
        startValue: 0.6,
      },
      {
        id: 'dNOveczZY4A',
        endValue: 0.4,
        color: '#CD061D',
        name: 'Poor',
        startValue: 0,
      },
      {
        id: 'ssrfhvzLFNI',
        endValue: 0.6,
        color: '#EDE722',
        name: 'Good',
        startValue: 0.4,
      },
    ],
  },
  {
    id: 'DN4G91iSpPs',
    name: 'Malaria positivity among Pregnance (5-100, 1-5,0-1)',
    legends: [
      {
        id: 'fB8PiRAiNg9',
        endValue: 1,
        color: '#64C205',
        name: 'Excellent',
        startValue: 0,
      },
      {
        id: 'DSpwZUlwJFP',
        endValue: 100,
        color: '#EC4205',
        name: 'Poor',
        startValue: 5,
      },
      {
        id: 'JpS9IF2Zys5',
        endValue: 5,
        color: '#F2EB1F',
        name: 'Good',
        startValue: 1,
      },
    ],
  },
  {
    id: 'U6Q5LWMzX7k',
    name: 'Malaria tested (0-50, 50-80, 80-150)',
    legends: [
      {
        id: 'nqStfFAFvyx',
        endValue: 80,
        color: '#FFFF00',
        name: 'Good',
        startValue: 50,
      },
      {
        id: 'OXM47nVINuk',
        endValue: 150,
        color: '#00B050',
        name: 'Excellent',
        startValue: 80,
      },
      {
        id: 'OQguPgx9bfL',
        endValue: 50,
        color: '#FF0000',
        name: 'Poor',
        startValue: 0,
      },
    ],
  },
  {
    id: 'ZlauVVShcJj',
    name: 'OPD visit outliers (50000-1000000,25000-50000,10000-25000)',
    legends: [
      {
        id: 'cPJzWrbhrNw',
        endValue: 25000,
        color: '#FCFF00',
        name: '1',
        startValue: 10000,
      },
      {
        id: 'wOHuLgQA6bo',
        endValue: 1000000,
        color: '#FF0000',
        name: '3',
        startValue: 50000,
      },
      {
        id: 'll1tpCfOYpT',
        endValue: 50000,
        color: '#FFA500',
        name: '2',
        startValue: 25000,
      },
    ],
  },
  {
    id: 'I137nMrl0vo',
    name: 'Outlier > 1,000',
    legends: [
      {
        id: 'MNgd2EyYVjI',
        endValue: 10000000,
        color: '#FF0800',
        name: 'Outlier > 1,000',
        startValue: 1000,
      },
    ],
  },
  {
    id: 'Pazmxqm3n1q',
    name: 'Outlier > 10,000',
    legends: [
      {
        id: 'zih0Iegw8EV',
        endValue: 10000000,
        color: '#FF0000',
        name: 'Outlier > 10,000',
        startValue: 10000,
      },
    ],
  },
  {
    id: 'Mk1K8Rr7kBR',
    name: 'Penta 1 outlier #4 (0-300,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'YGwwHQx6nrd',
        endValue: 1000000,
        color: '#FF0000',
        name: '> 5,000',
        startValue: 5000,
      },
      {
        id: 'jSWwd3XF33c',
        endValue: 1000,
        color: '#FFEC23',
        name: '300 to 1,000',
        startValue: 300,
      },
      {
        id: 'HiTyuWD79L7',
        endValue: 5000,
        color: '#FFA500',
        name: '1,000 to 5,000',
        startValue: 1000,
      },
      {
        id: 'W80cPqGyHFf',
        endValue: 300,
        color: 'TRANSPARENT',
        name: '< 300',
        startValue: 0,
      },
    ],
  },
  {
    id: 'nmSGl7f3rU9',
    name: 'Penta 1 outlier - # 3 (300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'OCI8dHf2iug',
        endValue: 5000,
        color: '#FFA500',
        name: '1,000 to 5,000',
        startValue: 1000,
      },
      {
        id: 'Jv5gmc8Cpib',
        endValue: 1000,
        color: '#FBFF5B',
        name: '300 to 1,000',
        startValue: 300,
      },
      {
        id: 'oOnn2gQpPJd',
        endValue: 1000000,
        color: '#FF0000',
        name: '> 5,000',
        startValue: 5000,
      },
    ],
  },
  {
    id: 'oD9tDuUXVeO',
    name: 'Penta 1 outlier - proportional (1-300,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'Nt8zPRIp6DA',
        endValue: 300,
        color: '#FEFDFB',
        name: '< 300',
        startValue: 1,
      },
      {
        id: 'tYRnz7uDzht',
        endValue: 1000000,
        color: '#FF4700',
        name: '> 5,000',
        startValue: 5000,
      },
      {
        id: 'PjKhEJMGorV',
        endValue: 5000,
        color: '#FFA500',
        name: '1,000 to 5,000',
        startValue: 1000,
      },
      {
        id: 'd7USfxLJKeX',
        endValue: 1000,
        color: '#FFFC00',
        name: '300 to 1,000',
        startValue: 300,
      },
    ],
  },
  {
    id: 'IZ3d2xCq7ae',
    name: 'Penta 1 outliers (0-300,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'xZT8LvJZ9Yp',
        endValue: 5000,
        color: '#FF9840',
        name: '2)',
        startValue: 1000,
      },
      {
        id: 'O9eeuQWxGVK',
        endValue: 300,
        color: 'TRANSPARENT',
        name: '4) No large outliers',
        startValue: 0,
      },
      {
        id: 'gSWZPQ3Dagp',
        endValue: 1000000,
        color: '#FB0000',
        name: '1)',
        startValue: 5000,
      },
      {
        id: 'VRGMAYw8mm8',
        endValue: 1000,
        color: '#FAFF00',
        name: '3)',
        startValue: 300,
      },
    ],
  },
  {
    id: 'kMD2q94iJAJ',
    name: 'Penta 1 outliers - # 5 (0-100,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'urtYuHuonwI',
        endValue: 5000,
        color: '#FFA500',
        name: '3 -',
        startValue: 1000,
      },
      {
        id: 'kAOYUx7bGwx',
        endValue: 10000000,
        color: '#FF0500',
        name: '4 -',
        startValue: 5000,
      },
      {
        id: 'EirpqvaRF0r',
        endValue: 1000,
        color: '#F4F100',
        name: '2 -',
        startValue: 300,
      },
      {
        id: 'Q2wM8Cjklir',
        endValue: 300,
        color: '#FCFCFC',
        name: '1 -',
        startValue: 0,
      },
    ],
  },
  {
    id: 'aGi1xvSfV0Z',
    name: 'Penta 1 outliers - #2 (0-300,300-1000,1000-5000,5000-1000000)',
    legends: [
      {
        id: 'pbtTQD79O2c',
        endValue: 300,
        color: '#FFFFFF',
        name: '< 300',
        startValue: 0,
      },
      {
        id: 'FGe2eYTPOaI',
        endValue: 1000000,
        color: '#FF0000',
        name: '> 5,000',
        startValue: 5000,
      },
      {
        id: 'rwQ1YZ0Npv9',
        endValue: 5000,
        color: '#FFA500',
        name: '1,000 to 5,000',
        startValue: 1000,
      },
      {
        id: 'a8puFW22XPy',
        endValue: 1000,
        color: '#F1FF37',
        name: '300 to 1,000',
        startValue: 300,
      },
    ],
  },
  {
    id: 'OaPCQL4tE0m',
    name: 'Prevalance (1.7-2.5,0.1-1.7,0-0.1)',
    legends: [
      {
        id: 'CpzJ7FLFJdx',
        endValue: 1.7,
        color: '#F4FF00',
        name: '0.1 - 1.7',
        startValue: 0.1,
      },
      {
        id: 'F50KcRpKyYT',
        endValue: 2.5,
        color: '#F90000',
        name: '1.7 - 2.5',
        startValue: 1.7,
      },
      {
        id: 'w4vyszoLDpi',
        endValue: 0.1,
        color: '#35F020',
        name: '0.0 - 0.8',
        startValue: 0,
      },
    ],
  },
  {
    id: 'RfHfBMPaSOB',
    name: 'Reporting Malaria (0-30,30-50,50-70,70-100)',
    legends: [
      {
        id: 'tlf5BFHW0cN',
        endValue: 30,
        color: '#FF0000',
        name: 'Low',
        startValue: 0,
      },
      {
        id: 'dBEWo1DZ2Xx',
        endValue: 50,
        color: '#FFC300',
        name: 'Mediam',
        startValue: 30,
      },
      {
        id: 'Fh10Gd2BunY',
        endValue: 70,
        color: '#97CE6A',
        name: 'Good',
        startValue: 50,
      },
      {
        id: 'KB1xbvn3UEs',
        endValue: 100,
        color: '#43922C',
        name: 'High',
        startValue: 70,
      },
    ],
  },
  {
    id: 'RVJUoXd7DOH',
    name: 'Severe Malaria Incidence (0-10,10-25,25-50,50-100,100-500)',
    legends: [
      {
        id: 'YfW9Ac6rZQM',
        endValue: 100,
        color: '#FDA909',
        name: '50 - < 100',
        startValue: 50,
      },
      {
        id: 'UvNEko3QS6v',
        endValue: 500,
        color: '#E8240E',
        name: '>100',
        startValue: 100,
      },
      {
        id: 'Y4OXQDfqGiU',
        endValue: 25,
        color: '#08FF00',
        name: '10 - < 25',
        startValue: 10,
      },
      {
        id: 'q8W338JwsHv',
        endValue: 50,
        color: '#F3EA0A',
        name: '25 - < 50',
        startValue: 25,
      },
      {
        id: 'K7DmrnXep3g',
        endValue: 10,
        color: '#399313',
        name: '<10',
        startValue: 0,
      },
    ],
  },
  {
    id: 'sM9apMo8REk',
    name: 'Star Rating Assessment(SRA) Cut-Off Points(Legend Set)',
    legends: [
      {
        id: 'RzpaaKut8IL',
        endValue: 101,
        color: '#008000',
        name: '90 - 100',
        startValue: 90,
      },
      {
        id: 'aIb02d4rT9u',
        endValue: 20,
        color: '#FF0000',
        name: '0 - 20',
        startValue: 0,
      },
      {
        id: 'aMNoewmcrAh',
        endValue: 60,
        color: '#FEB24C',
        name: '40 - 60',
        startValue: 40,
      },
      {
        id: 'qKMgWtOhssa',
        endValue: 90,
        color: '#82F020',
        name: '80 - 90',
        startValue: 80,
      },
      {
        id: 'xLJzK9N9sm0',
        endValue: 40,
        color: '#F06C6C',
        name: '20 - 40',
        startValue: 20,
      },
      {
        id: 'h4nRa7b1hxN',
        endValue: 1000,
        color: '#0000FF',
        name: '100 - 1000',
        startValue: 101,
      },
      {
        id: 'QBM03W13fl7',
        endValue: 80,
        color: '#FDF03C',
        name: '60 - 80',
        startValue: 60,
      },
    ],
  },
  {
    id: 'vI53B9THfXK',
    name: 'Star Rating Assessment(SRA) Legend Set',
    legends: [
      {
        id: 'IP9dkvMr9ar',
        endValue: 100,
        color: '#008000',
        name: '90 - 100',
        startValue: 90,
      },
      {
        id: 'Ty4Sb2aTaJy',
        endValue: 1000,
        color: '#0000FF',
        name: '100 - 1000',
        startValue: 100,
      },
      {
        id: 'OHWn7m2nQmQ',
        endValue: 80,
        color: '#FDF03C',
        name: '60 - 80',
        startValue: 60,
      },
      {
        id: 'zCSUbWVdrPS',
        endValue: 40,
        color: '#F06C6C',
        name: '20 - 40',
        startValue: 20,
      },
      {
        id: 'Et2JOaoqkzv',
        endValue: 90,
        color: '#82F020',
        name: '80 - 90',
        startValue: 80,
      },
      {
        id: 'rTGnh3lPRn0',
        endValue: 60,
        color: '#FEB24C',
        name: '40 - 60',
        startValue: 40,
      },
      {
        id: 'CTawpfz26TQ',
        endValue: 20,
        color: '#FF0000',
        name: '0 - 20',
        startValue: 0,
      },
    ],
  },
  {
    id: 'NSOv1YyEfE4',
    name: 'Star Rating(0-17,17-33,33-50,50-67,67-83,83-100)',
    legends: [
      {
        id: 'ck6geWL2L9F',
        endValue: 50,
        color: '#fee08b',
        name: '2 - Star',
        startValue: 33,
      },
      {
        id: 'bkqSF2UtTVP',
        endValue: 100,
        color: '#1a9850',
        name: '5 - Star',
        startValue: 83,
      },
      {
        id: 'chklDMAcRzo',
        endValue: 17,
        color: '#d73027',
        name: '0 - Star',
        startValue: 0,
      },
      {
        id: 'bCeq36QEI5q',
        endValue: 33,
        color: '#fc8d59',
        name: '1 - Star',
        startValue: 17,
      },
      {
        id: 'l9fYyBgRm0B',
        endValue: 67,
        color: '#d9ef8b',
        name: '3 - Star',
        startValue: 50,
      },
      {
        id: 'Kw6IFGk8hue',
        endValue: 83,
        color: '#91cf60',
        name: '4 - Star',
        startValue: 67,
      },
    ],
  },
  {
    id: 'jo4g5mOxokG',
    name: 'Very large PCV 3 outlier (> 1000)',
    legends: [
      {
        id: 'KC9tLzQTZXL',
        endValue: 1,
        color: '#2BFF00',
        name: 'PCV 3 outlier > 1,000',
        startValue: 1,
      },
    ],
  },
  {
    id: 'EsOqZREB1Qc',
    name: 'Very large Penta 1 outlier (> 1000)',
    legends: [
      {
        id: 'z2x5vL4VilI',
        endValue: 1,
        color: '#FFA500',
        name: 'Penta 1 outlier > 1,000',
        startValue: 1,
      },
    ],
  },
  {
    id: 'x86nCiopkC8',
    name: 'Very large Penta 3 outlier (> 1000)',
    legends: [
      {
        id: 'RkrVfWX9wHu',
        endValue: 1,
        color: '#FF0B00',
        name: 'Penta 3 outlier > 1,000',
        startValue: 1,
      },
    ],
  },
];
